# All the generic configuration goes here. By default the active profile is 'development'.
# To override specific profile please pass '-Dspring.profiles.active=production' as VM args
spring:
  profiles:
    active: development
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    testOnBorrow: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

jwt:
  header: Authorization
  secret: mySecret
  expiration: 6000

# Spring-boot actuator endpoints
management:
  context-path: /app

server:
  compression:
    enabled: true
    mime-types:
      - application/json

# Liquibase change-log path containing the migrations
liquibase:
  change-log: classpath:/migrations/sql/db.changelog-master.yaml
---
# <----- Development profile ------>
spring:
  profiles: development
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/heybeachdb
    username: sa
    password:

---
# <----- Production profile ------>
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://xxxx/heybeach # Replace xxxx with database hostname
    username: xxxxx                      # Replace xxxx with database username
    password: xxxxx                      # Replace xxxx with database password

---
# <----- test profile ------>
spring:
  profiles: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/heybeachtestdb;AUTO_SERVER=TRUE
    username: sa
    password:

jwt:
  header: Authorization
  expiration: 60000