spring:
  profiles:
    active: development
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    testOnBorrow: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 6000
  route:
    authentication:
      path: auth
      refresh: refresh

# Spring-boot actuator endpoints
management:
  context-path: /app

server:
  compression:
    enabled: true
    mime-types:
      - application/json

# Liquibase change-log path containing the migrations
liquibase:
  change-log: classpath:/migrations/sql/db.changelog-master.yaml

datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:~/heybeachdb
      username: sa
      password:

#logging:
#  level:
#    org.springframework:
#      security: DEBUG