# All the generic configuration goes here. By default the active profile is 'development'.
# To override specific profile please pass '-Dspring.profiles.active=production' as VM args
spring:
  profiles:
    active: development
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    testOnBorrow: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 6000
  route:
    authentication:
      path: auth
      refresh: refresh

# Spring-boot actuator endpoints
management:
  context-path: /app

server:
  compression:
    enabled: true
    mime-types:
      - application/json

# Liquibase change-log path containing the migrations
liquibase:
  change-log: classpath:/migrations/sql/db.changelog-master.yaml

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
---
# <----- Development profile ------>
spring:
  profiles: development
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/heybeachdb
        username: sa
        password:

---
# <----- Production profile ------>
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://xxxx/heybeach # Replace xxxx with database hostname
    username: xxxxx
    password: xxxxx

---
# <----- test profile ------>
spring:
  profiles: test

  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/heybeachdb
        username: sa
        password:

jwt:
  header: Authorization
  expiration: 60000